### ISSUE TITLE
[5] Incorrect ISBN number

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#20]
After typing too long ISBN number - exception occured without any information for user.

Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(13)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	... 57 more

![image](https://user-images.githubusercontent.com/26207880/37371641-562d03c6-2710-11e8-9bc8-a4d0405277e2.png)

**Comment by JaRutkowski** [comment]
Done and merged.
