### ISSUE TITLE
[30] Settings window - NoSuchElementException

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#280]
Once the 'Settings' window is opened for one user, then an error occurs for other users when they are trying to open the 'Settings' window, with the following error: 

```
Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:141)
	at com.javafee.elibrary.core.common.Constants$Panel_Settings.getByName(Constants.java:36)
	at com.javafee.elibrary.core.settingsform.Actions.reloadContentPanel(Actions.java:55)
	at com.javafee.elibrary.core.settingsform.Actions.setFirstNodeSelectionInTreeMenu(Actions.java:146)
	at com.javafee.elibrary.core.settingsform.Actions.initializeForm(Actions.java:47)
	at com.javafee.elibrary.core.settingsform.Actions.control(Actions.java:20)
	at com.javafee.elibrary.core.tabbedform.Actions.openSettingsForm(Actions.java:264)
	at com.javafee.elibrary.core.tabbedform.Actions.onClickBtnSettings(Actions.java:241)
	at com.javafee.elibrary.core.tabbedform.Actions.lambda$control$2(Actions.java:32)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
```

Additionally, for the super admin user below error occurred (after the 'Settings' window was closed), but **was not reproduced again** yet.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.javafee.elibrary.core.settingsform.Actions$1.windowClosed(Actions.java:29)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosed(AWTEventMulticaster.java:368)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosed(AWTEventMulticaster.java:367)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosed(AWTEventMulticaster.java:367)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2071)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
```

**Comment by AKepska** [comment]
Cannot reproduce the bug.
