### ISSUE TITLE
[5] Non-unique inventory number

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#6]
As Librarian :

Exception during volume addition using non-unique value of inventory number. There is no exception information for user. Check in another places.

Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uke0qjrny61yxgd59ny89bl1dx2"
  Szczegóły: Key (inventory_number)=(0000000000005) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	... 58 more

![image](https://user-images.githubusercontent.com/26207880/37229080-23c2a128-23e3-11e8-805d-8160a4db7b49.png)

**Comment by JaRutkowski** [comment]
Done and merged.
