### ISSUE TITLE
[5] NPE during saving to template library in Admin context

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#67]
`
Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.javafee.hibernate.dao.common.Common.checkAndGetSystemProperties(Common.java:86)
`

**Comment by JaRutkowski** [comment]
Cause of the situation is the fact, that in the test DB record for admin role was not found. It should be solved by realization of system parameters and system data handling.

**Comment by JaRutkowski** [comment]
Solved as part of #31.
