### ISSUE TITLE
[5] User removal - not-null property references (e-mail)

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#7]
As Librarian :

Exception during user removal. In #1 e-mail property was added with no actualisation for existing user in db. Can be resolved.

Caused by: org.hibernate.PropertyValueException: not-null property references a null or transient value : com.javafee.hibernate.dto.library.Client.eMail
	at org.hibernate.engine.internal.Nullability.checkNullability(Nullability.java:92)
	at org.hibernate.event.internal.DefaultDeleteEventListener.deleteEntity(DefaultDeleteEventListener.java:261)
	at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:142)
	at org.hibernate.event.internal.DefaultDeleteEventListener.onDelete(DefaultDeleteEventListener.java:56)
	at org.hibernate.internal.SessionImpl.fireDelete(SessionImpl.java:993)
	... 39 more

![image](https://user-images.githubusercontent.com/26207880/37229174-6350a7c2-23e3-11e8-8396-e1106512c03d.png)

**Comment by JaRutkowski** [comment]
Done and merged. 

Notnull in domain class changed to true.
