### ISSUE TITLE
[1] Problem with registration approval

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#80]
After executing such sequence - firstly, as 'accountant' new worker registration. next administrator role granting and registration approval - exception as belo occure.

```
Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
	at com.javafee.hibernate.dto.library.Worker.toString(Worker.java:65)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
```

**Comment by JaRutkowski** [comment]
Solved as part of #93.
