### ISSUE TITLE
[50] Null pointer after log out

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#9]
As Librarian :

Null pointer after log out.

Exception in thread "Timer-0" java.lang.NullPointerException
	at com.javafee.tabbedform.Actions$1.run(Actions.java:47)
	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
	at java.base/java.util.TimerThread.run(Unknown Source)

**Comment by JaRutkowski** [comment]
Check for Thread safe-stop.

**Comment by JaRutkowski** [comment]
Task connected to #35 [5] Event loading after log out.

**Comment by JaRutkowski** [comment]
Closed.
