### ISSUE TITLE
[1] Critical StackOverflowError in worker

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#93]
Test scenario path:

- Login into the system as super user (Administrator);
- Navigate to 'Workers' tab;
- Change state of check box 'Administrator' and click 'Accept to apply the changes;
- Change state of check box 'Administrator' and click 'Accept to apply the changes again.

Test scenario description:
After double state change of check box 'Administrator' exception occurs in the logs console (StackOverflowError). After exception is thrown, user is not able to f.eg. approve Wokrer registration, add new book (on 'Books', after clicking 'Add' button, frame is not opened), log in into the system after log off. It's critical bug, that needs user to make system restart.

_Form:_
![image](https://user-images.githubusercontent.com/26207880/73071715-ceee1900-3eb3-11ea-9e18-c643fe1ad1fb.png)

_First 'Administrator' change:_
![image](https://user-images.githubusercontent.com/26207880/73071865-28564800-3eb4-11ea-86e9-5e7d14ec959b.png)

_Second 'Administrator' change:_
![image](https://user-images.githubusercontent.com/26207880/73071921-458b1680-3eb4-11ea-9ec2-6f30a7d52681.png)

_Stack trace:_
```
2020-01-24 14:17:10 DEBUG AbstractLoadPlanBasedCollectionInitializer:105 - Done loading collection
Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:91)
	at com.javafee.hibernate.dto.library.LibraryWorkerId.toString(LibraryWorkerId.java:11)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at com.javafee.hibernate.dto.library.LibraryWorker.toString(LibraryWorker.java:16)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:473)
	at org.hibernate.collection.internal.PersistentSet.toString(PersistentSet.java:328)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at com.javafee.hibernate.dto.library.LibraryData.toString(LibraryData.java:22)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at com.javafee.hibernate.dto.library.LibraryWorkerId.toString(LibraryWorkerId.java:11)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at com.javafee.hibernate.dto.library.LibraryWorker.toString(LibraryWorker.java:16)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:473)
	at org.hibernate.collection.internal.PersistentSet.toString(PersistentSet.java:328)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at com.javafee.hibernate.dto.library.LibraryData.toString(LibraryData.java:22)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at com.javafee.hibernate.dto.library.LibraryWorkerId.toString(LibraryWorkerId.java:11)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at com.javafee.hibernate.dto.library.LibraryWorker.toString(LibraryWorker.java:16)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at java.base/java.util.AbstractCollection.toString(AbstractCollection.java:473)
	at org.hibernate.collection.internal.PersistentSet.toString(PersistentSet.java:328)
	at java.base/java.lang.String.valueOf(String.java:2788)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
```

**Comment by JaRutkowski** [comment]
Done by removing object cloning before updating.
